import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Activity, AlertTriangle, Bell, ChevronDown, ChevronLeft, ChevronRight, Clock3, FileText, Filter, Hourglass, LayoutDashboard, Menu, Moon, MoreHorizontal, Search, Settings, Sun, Users, X, XCircle } from 'lucide-react';

type Stage = 'Manager Approval' | 'Finance Review' | 'Director Approval';
type Status = 'Ready for Finance' | 'Waiting for Manager' | 'Under Review' | 'Needs Documents' | 'Approved' | 'Rejected';
type Priority = 'Urgent' | 'High' | 'Normal';
type Request = { id: string; employee: string; department: string; submittedAt: string; amount: number; priority: Priority; stage: Stage; status: Status; waitingHours: number; reviewer: string | null; recommendedAction: string; reason: string };
type Response<T> = { data: T; total?: number; page?: number; pageSize?: number };
type Filters = { search: string; department: string; stage: string; amount: string; submission: string; status: string; priority: string };
type Summary = { totalRequested: number; approved: number; pendingAmount: number; rejected: number; total: number; pending: number; urgent: number; waitingManager: number; waitingFinance: number; stages: Record<Stage, number>; completed: number; sla: number; directorAmount: number; financeReviewAmount: number; missingDocs: number; managerSla: number };
type Dialog = { kind: 'approve' | 'reject' | 'assign' | 'detail'; ids: string[]; request?: Request } | null;
const blank: Filters = { search: '', department: '', stage: '', amount: '', submission: '', status: '', priority: '' };
const money = (n: number) => `Rp ${new Intl.NumberFormat('id-ID').format(n)}`;
const compact = (n: number) => `Rp ${(n / 1e6).toFixed(1)}M`;
const fmtDuration = (hours: number) => `${Math.floor(hours)}h ${String(Math.round((hours % 1) * 60)).padStart(2, '0')}m`;
const api = 'http://localhost:4174/api';
const scenario = new URLSearchParams(location.search).get('scenario');

function App() {
  const [filters, setFilters] = useState<Filters>(() => { try { return { ...blank, ...JSON.parse(localStorage.getItem('finflow-view') || '{}') }; } catch { return blank; } });
  const [requests, setRequests] = useState<Request[]>([]); const [summary, setSummary] = useState<Summary | null>(null);
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(5); const [total, setTotal] = useState(0);
  const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [pendingOnly, setPendingOnly] = useState(false);
  const [slaOnly, setSlaOnly] = useState(false);
  const [dialog, setDialog] = useState<Dialog>(null); const [reason, setReason] = useState(''); const [reviewer, setReviewer] = useState(''); const [menuId, setMenuId] = useState(''); const [drawer, setDrawer] = useState(false); const [dark, setDark] = useState(false);
  const dialogTrigger = useRef<HTMLElement | null>(null); const dialogHeading = useRef<HTMLHeadingElement>(null);
  const queryString = useMemo(() => new URLSearchParams({ ...filters, ...(pendingOnly ? { pendingOnly: 'true' } : {}), ...(slaOnly ? { slaOnly: 'true' } : {}), page: String(page), pageSize: String(pageSize), ...(scenario ? { scenario } : {}) }).toString(), [filters, page, pageSize, pendingOnly, slaOnly]);
  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const endpoint = scenario === 'network-error' ? 'http://localhost:4175/api' : api;
      const [listRes, sumRes] = await Promise.all([fetch(`${endpoint}/requests?${queryString}`), fetch(`${endpoint}/summary`)]);
      if (!listRes.ok || !sumRes.ok) throw new Error(!listRes.ok ? `Request list failed (${listRes.status})` : `Summary failed (${sumRes.status})`);
      const list: Response<Request[]> = await listRes.json(); const next: Summary = await sumRes.json();
      setRequests(list.data); setTotal(list.total ?? 0); setSummary(next); setSelected([]);
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load requests.'); setRequests([]); }
    finally { setLoading(false); }
  }, [queryString]);
  // Fetching when query state changes is this page's API synchronization boundary.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (dialog) { dialogHeading.current?.focus(); const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') closeDialog(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); } }, [dialog]);
  function closeDialog() { setDialog(null); setReason(''); setReviewer(''); window.setTimeout(() => dialogTrigger.current?.focus(), 0); }
  function openDialog(d: NonNullable<Dialog>, trigger?: HTMLElement) { dialogTrigger.current = trigger ?? document.activeElement as HTMLElement; setDialog(d); }
  function updateFilter(key: keyof Filters, value: string) { setPage(1); setPendingOnly(false); setSlaOnly(false); setFilters(prev => ({ ...prev, [key]: value })); }
  function saveView(value: string) { if (value === 'save') { localStorage.setItem('finflow-view', JSON.stringify(filters)); return; } if (value === 'my') { try { setPage(1); setPendingOnly(false); setSlaOnly(false); setFilters({ ...blank, ...JSON.parse(localStorage.getItem('finflow-view') || '{}') }); } catch { setFilters(blank); } } else if (value === 'reset') { setPage(1); setPendingOnly(false); setSlaOnly(false); setFilters(blank); } }
  async function mutate(action: 'approve' | 'reject' | 'assign', ids: string[]) {
    if (action === 'reject' && !reason.trim()) return;
    if (action === 'assign' && !reviewer) return;
    setBusy(true);
    try {
      const results = await Promise.all(ids.map(async id => { const res = await fetch(`${api}/requests/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, reason, reviewer }) }); if (!res.ok) { const body = await res.json(); throw new Error(body.message || `Update failed (${res.status})`); } return res.json() as Promise<Request>; }));
      setRequests(prev => prev.map(row => results.find(r => r.id === row.id) ?? row)); setSelected([]); setDialog(null); setReason(''); setReviewer('');
      const s = await fetch(`${api}/summary`); if (s.ok) setSummary(await s.json());
      window.setTimeout(() => dialogTrigger.current?.focus(), 0);
    } catch (e) { setError(e instanceof Error ? e.message : 'Action failed.'); }
    finally { setBusy(false); }
  }
  function exportCsv() { const rows = requests.filter(r => selected.includes(r.id)); const csv = ['Request ID,Employee,Department,Submitted,Amount,Priority,Stage,Status', ...rows.map(r => [r.id, r.employee, r.department, r.submittedAt, r.amount, r.priority, r.stage, r.status].map(v => `"${String(v).replace(/"/g, '""')}"`).join(','))].join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'finflow-selected-requests.csv'; a.click(); URL.revokeObjectURL(a.href); }
  function alertFilter(type: string) { if (type === 'pending') { setPendingOnly(true); setSlaOnly(false); setPage(1); } else if (type === 'urgent') { setPendingOnly(false); setSlaOnly(true); setPage(1); } else if (type === 'manager') updateFilter('status', 'Waiting for Manager'); else if (type === 'finance') updateFilter('stage', 'Finance Review'); else updateFilter('submission', 'today'); document.getElementById('queue')?.scrollIntoView({ behavior: 'smooth' }); }
  const pages = Math.max(1, Math.ceil(total / pageSize)); const actionable = requests.filter(r => !['Approved','Rejected'].includes(r.status)); const allSelected = actionable.length > 0 && actionable.every(r => selected.includes(r.id));
  return <div className={dark ? 'app dark' : 'app'}>
    {drawer && <button aria-label="Close navigation" className="scrim" onClick={() => setDrawer(false)} />}
    <aside className={`sidebar ${drawer ? 'show' : ''}`}><div className="brand"><span className="brand-mark">$</span><b>Finflow</b><button className="icon-btn drawer-close" aria-label="Close menu" onClick={() => setDrawer(false)}><X size={18}/></button></div>
      <nav aria-label="Main navigation" className="nav">{[[LayoutDashboard,'Dashboard',''],[FileText,'Reimbursements','197'],[Users,'Employees',''],[Activity,'Reports',''],[Settings,'Settings','']].map(([Icon,label,badge]: any) => <button key={label} disabled={label !== 'Reimbursements'} title={label !== 'Reimbursements' ? 'Unavailable in this demo' : undefined} className={`nav-item ${label === 'Reimbursements' ? 'active' : ''}`} aria-current={label === 'Reimbursements' ? 'page' : undefined}><Icon size={19}/><span>{label}</span>{badge && <small>{badge}</small>}</button>)}</nav>
      <div className="sidebar-user"><div className="avatar">RM</div><div><b>Finance Admin</b><small>Finance Operations</small></div><ChevronDown size={16}/></div>
    </aside>
    <main className="main"><header className="topbar"><button className="icon-btn mobile-menu" aria-label="Open navigation" onClick={() => setDrawer(true)}><Menu size={20}/></button><label className="global-search"><Search size={15}/><input placeholder="Search..." aria-label="Search queue" value={filters.search} onChange={e => updateFilter('search', e.target.value)}/></label><div className="top-actions"><button className="icon-btn" aria-label={dark ? 'Switch to light theme' : 'Switch to dark theme'} onClick={() => setDark(!dark)}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</button><button className="icon-btn" aria-label="Notifications unavailable" title="Notifications unavailable in this demo" disabled><Bell size={17}/></button><div className="top-profile"><div className="avatar orange">FA</div><div><b>Finance Admin</b><small>Finance Operations</small></div></div></div></header>
      <div className="content"><section className="page-heading"><div className="breadcrumbs"><span>Reimbursements</span><ChevronRight size={16}/><b>Approval Queue</b></div><h1>Approval Queue</h1><p>{summary?.pending ?? '…'} requests require attention · {compact(summary?.pendingAmount ?? 0)} awaiting decision</p></section>
        <section className="card overview"><div className="section-head"><h2>Finance Overview</h2><span>Current reimbursement workload · August 2026</span></div><div className="metric-grid">{[['Total requested amount',summary?.totalRequested ?? 0,`${summary?.total ?? 0} submitted requests`,''],['Total approved amount',summary?.approved ?? 0,`${summary?.total ? Math.round((summary.approved/summary.totalRequested)*100) : 0}% of submitted value`,'green'],['Total pending amount',summary?.pendingAmount ?? 0,`${summary?.pending ?? 0} awaiting decision`,'amber'],['Total rejected amount',summary?.rejected ?? 0,`${summary?.totalRequested ? ((summary.rejected/summary.totalRequested)*100).toFixed(1) : 0}% of submitted value`,'red']].map(([label,value,sub,color]: any)=><div className="metric" key={label}><span className={color}>{label}</span><strong>{compact(value)}</strong><small>{sub}</small></div>)}</div></section>
        <section className="workload"><h2>Today’s workload</h2><div className="work-grid">{[[Clock3,'Pending approval',summary?.pending ?? 0,'Requests awaiting decision','slate','pending'],[Bell,'Urgent requests',summary?.urgent ?? 0,'Requires action today','red','urgent'],[Hourglass,'Waiting Manager',summary?.waitingManager ?? 0,`${summary?.managerSla ?? 0} waiting over 3 days`,'amber','manager'],[Hourglass,'Waiting finance',summary?.waitingFinance ?? 0,'Awaiting finance review','amber','finance']].map(([Icon,label,count,detail,tone,filter]: any)=><article className="card work-card" key={label}><div className="work-title"><Icon size={15} className={tone}/>{label}</div><strong>{count}</strong><small>{detail}</small><button className="primary" onClick={() => alertFilter(filter)}>View Detail <ChevronRight size={14}/></button></article>)}</div></section>
        <div className="pipeline-grid"><section className="card pipeline"><div className="section-head"><h2>Approval pipeline</h2><span>{summary?.pending ?? 0} active requests</span></div><div className="steps">{[['Employee submission',String(summary?.total ?? 0),'This month','done'],['Manager approval',String(summary?.stages['Manager Approval'] ?? 0),`${summary?.waitingManager ?? 0} waiting`,'alert'],['Finance verification',String(summary?.stages['Finance Review'] ?? 0),'Pending review','pending'],['Director approval',String(summary?.stages['Director Approval'] ?? 0),`${compact(summary?.directorAmount ?? 0)} pending`,'pending'],['Completed',String(summary?.completed ?? 0),'This month','done']].map(([name,count,sub,state])=><div className="step" key={name}><span className={`step-icon ${state}`}>{state==='done'?'✓':state==='alert'?'!':'•'}</span><b>{name}</b><strong>{count}</strong><small>{sub}</small></div>)}</div></section>
          <section className="card sla"><h2>SLA &amp; bottlenecks</h2>{[[`${summary?.sla ?? 0} requests approaching SLA`,'Review now','urgent'],[`${summary?.waitingManager ?? 0} waiting on Manager (${summary?.managerSla ?? 0} over 3 days)`,'Escalate','manager'],[`${compact(summary?.directorAmount ?? 0)} awaiting Director approval`,'View requests','finance'],[`${summary?.missingDocs ?? 0} missing supporting documents`,'Request revision','']].map(([copy,action,key],i)=><div className="sla-row" key={copy}><i className={i<2?'dot red-dot':'dot amber-dot'}/><span>{copy}</span><button disabled={!key} onClick={() => key && alertFilter(key)}>{action}</button></div>)}</section></div>
        <section className="priority"><div className="priority-intro"><b>Priority alerts</b><span>Start with work that risks delay or requires escalation.</span></div>{[[AlertTriangle,`${summary?.sla ?? 0} requests approaching SLA`,'Requests waiting at least 24 hours','urgent','yellow'],[Hourglass,`${summary?.waitingManager ?? 0} requests waiting on Manager`,`${summary?.managerSla ?? 0} have waited longer than 3 days`,'manager','orange'],[Activity,`${compact(summary?.financeReviewAmount ?? 0)} needs finance review`,'Total pending in finance review','finance','blue']].map(([Icon,title,detail,key,tone]: any)=><div className="priority-item" key={title}><span className={`priority-icon ${tone}`}><Icon size={17}/></span><div><b>{title}</b><small>{detail}</small><button onClick={() => alertFilter(key)}>Review now</button></div></div>)}</section>
        <section className="card queue" id="queue"><div className="queue-heading"><h2>Approval Queue</h2><label className="queue-search"><Search size={15}/><input placeholder="Search Employee or request ID" aria-label="Search employee or request ID" value={filters.search} onChange={e => updateFilter('search',e.target.value)}/></label></div>
          <div className="filters">{[['department','Department','All Department',['Sales','Product','Engineering','Marketing','Operations','People']],['stage','Approval Stage','All Stage',['Manager Approval','Finance Review','Director Approval']],['amount','Amount','Any Amount',['Under Rp 10M','Rp 10M – 25M','Over Rp 25M']],['submission','Submission','Any Time',['Today','This week','This month']],['status','Status','All Statuses',['Ready for Finance','Waiting for Manager','Under Review','Needs Documents','Approved','Rejected']]].map(([key,label,placeholder,opts]: any)=><label key={key}>{label}<select value={(filters as any)[key] === 'under10' ? 'Under Rp 10M' : (filters as any)[key] === '10to25' ? 'Rp 10M – 25M' : (filters as any)[key] === 'over25' ? 'Over Rp 25M' : (filters as any)[key] === 'today' ? 'Today' : (filters as any)[key] === 'week' ? 'This week' : (filters as any)[key] || ''} onChange={e => { const val = e.target.value; const mapped = key === 'amount' ? ({'Under Rp 10M':'under10','Rp 10M – 25M':'10to25','Over Rp 25M':'over25'} as any)[val] || '' : key === 'submission' ? ({Today:'today','This week':'week'} as any)[val] || '' : val; updateFilter(key,mapped); }}><option value="">{placeholder}</option>{opts.map((o: string)=><option key={o}>{o}</option>)}</select></label>)}
            <label>Save View<select value="" aria-label="Save View" onChange={e => saveView(e.target.value)}><option value="">My Work</option><option value="save">Save current filters</option><option value="my">Load saved view</option><option value="reset">Reset filters</option></select></label>
          </div>
          <div className="bulk"><label className="check-label"><input type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? [] : actionable.map(r=>r.id))} aria-label="Select all pending requests on this page"/>{selected.length} Selected</label><div className="bulk-actions"><button disabled={!selected.length || busy} onClick={e => openDialog({kind:'assign',ids:selected},e.currentTarget)}>Assign Reviewer</button><button disabled={!selected.length || busy} onClick={e => openDialog({kind:'approve',ids:selected},e.currentTarget)}>Approve</button><button disabled={!selected.length || busy} onClick={e => openDialog({kind:'reject',ids:selected},e.currentTarget)}>Reject</button><button disabled={!selected.length} onClick={exportCsv}>Report</button></div></div>
          {error && <div className="error-banner" role="alert"><XCircle size={17}/><span>{error}</span><button onClick={() => void load()}>Retry</button></div>}
          <div className="table-wrap"><table><thead><tr><th className="select-col"><span className="sr-only">Select</span></th><th>Employee</th><th>Department</th><th>Submitted</th><th>Amount</th><th>Priority</th><th>Approval<br/>Stage</th><th>Current<br/>Status</th><th>Waiting Duration</th><th>Recommended Action</th><th aria-label="More actions"/></tr></thead><tbody>
          {loading ? <tr><td colSpan={11} className="table-message"><span className="spinner"/>Loading approval requests…</td></tr> : requests.length === 0 ? <tr><td colSpan={11} className="table-message"><Filter size={19}/><b>No requests found</b><span>Try another search or reset the filters.</span><button onClick={() => { setFilters(blank); setPage(1); setPendingOnly(false); setSlaOnly(false); }}>Reset filters</button></td></tr> : requests.map(r=><tr key={r.id}><td><input type="checkbox" disabled={r.status==='Approved'||r.status==='Rejected'} checked={selected.includes(r.id)} onChange={() => setSelected(s=>s.includes(r.id)?s.filter(id=>id!==r.id):[...s,r.id])} aria-label={`Select ${r.employee} ${r.id}`}/></td><td><button className="employee" onClick={e => openDialog({kind:'detail',ids:[r.id],request:r},e.currentTarget)}>{r.employee}</button><small>{r.id}</small></td><td>{r.department}</td><td>{new Date(r.submittedAt).toLocaleDateString('en-US',{month:'short',day:'2-digit'})}, {new Date(r.submittedAt).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false})}</td><td className="amount">{money(r.amount)}</td><td><span className={`badge ${r.priority.toLowerCase()}`}><i/> {r.priority}</span></td><td className="stage-cell">{r.stage}</td><td><span className="status"><i className={r.status==='Ready for Finance'?'blue-dot':r.status==='Approved'?'green-dot':r.status==='Rejected'?'red-dot':'amber-dot'}/>{r.status}</span></td><td className={r.waitingHours >= 5?'duration overdue':'duration'}>{fmtDuration(r.waitingHours)}</td><td><button className="outline-action" disabled={r.status==='Approved'||r.status==='Rejected'} onClick={e => r.recommendedAction==='Approve' ? openDialog({kind:'approve',ids:[r.id]},e.currentTarget) : openDialog({kind:'detail',ids:[r.id],request:r},e.currentTarget)}>{r.status==='Approved'?'Approved':r.status==='Rejected'?'Rejected':r.recommendedAction}</button></td><td className="more-cell"><button className="icon-btn" aria-label={`More actions for ${r.id}`} onClick={() => setMenuId(menuId===r.id?'':r.id)}><MoreHorizontal size={19}/></button>{menuId===r.id&&<div className="row-menu"><button onClick={e=>{setMenuId('');openDialog({kind:'detail',ids:[r.id],request:r},e.currentTarget)}}>View details</button><button disabled={r.status==='Approved'||r.status==='Rejected'} onClick={e=>{setMenuId('');openDialog({kind:'approve',ids:[r.id]},e.currentTarget)}}>Approve</button><button disabled={r.status==='Approved'||r.status==='Rejected'} onClick={e=>{setMenuId('');openDialog({kind:'reject',ids:[r.id]},e.currentTarget)}}>Reject</button></div>}</td></tr>)}
          </tbody></table></div>
          <div className="pagination"><span>Showing {total===0?0:(page-1)*pageSize+1} to {Math.min(page*pageSize,total)} of {total} results</span><label>Per page <select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option>5</option><option>10</option><option>20</option></select></label><div className="page-buttons"><button disabled={page===1} aria-label="Previous page" onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>Page {page} of {pages}</span><button disabled={page>=pages} aria-label="Next page" onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div>
        </section>
      </div>
    </main>
    {dialog && <div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget) closeDialog()}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button className="icon-btn dialog-close" aria-label="Close dialog" onClick={closeDialog}><X size={18}/></button>
      {dialog.kind==='detail' ? <><h2 id="dialog-title" ref={dialogHeading} tabIndex={-1}>Request details</h2><p className="dialog-sub">{dialog.request?.id} · {dialog.request?.employee}</p><dl className="details"><dt>Department</dt><dd>{dialog.request?.department}</dd><dt>Amount</dt><dd>{dialog.request&&money(dialog.request.amount)}</dd><dt>Approval stage</dt><dd>{dialog.request?.stage}</dd><dt>Current status</dt><dd>{dialog.request?.status}</dd><dt>Recommended action</dt><dd>{dialog.request?.recommendedAction}</dd>{dialog.request?.reviewer&&<><dt>Reviewer</dt><dd>{dialog.request.reviewer}</dd></>}</dl><div className="dialog-buttons"><button className="secondary" onClick={closeDialog}>Close</button></div></> : dialog.kind==='assign' ? <><h2 id="dialog-title" ref={dialogHeading} tabIndex={-1}>Assign reviewer</h2><p className="dialog-sub">Choose a reviewer for {dialog.ids.length} selected request{dialog.ids.length===1?'':'s'}.</p><label className="dialog-field">Reviewer<select value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">Select a reviewer</option><option>Amira Putri</option><option>Fajar Nugraha</option><option>Rizki Maulana</option></select></label><div className="dialog-buttons"><button className="secondary" onClick={closeDialog}>Cancel</button><button className="primary" disabled={!reviewer||busy} onClick={()=>void mutate('assign',dialog.ids)}>{busy?'Assigning…':'Assign reviewer'}</button></div></> : <><h2 id="dialog-title" ref={dialogHeading} tabIndex={-1}>{dialog.kind==='approve'?'Approve request':'Reject request'}</h2><p className="dialog-sub">{dialog.kind==='approve'?'Confirm that this request meets the approval criteria.':'A rejection reason is required and will be saved with the request.'}</p>{dialog.kind==='reject'&&<label className="dialog-field">Rejection reason<textarea autoFocus value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why this request is being rejected" rows={4}/></label>}<div className="dialog-buttons"><button className="secondary" onClick={closeDialog}>Cancel</button><button className={dialog.kind==='reject'?'danger':'primary'} disabled={busy||(dialog.kind==='reject'&&!reason.trim())} onClick={()=>void mutate(dialog.kind as 'approve'|'reject',dialog.ids)}>{busy?'Saving…':dialog.kind==='approve'?'Confirm approval':'Reject request'}</button></div></>}
    </section></div>}
  </div>;
}
export default App;
